version: '2.1'
services:

  hub:
    container_name: hub
    image: pojo-hub:latest
    build:
      context: .
      dockerfile: Dockerfile-hub
    ports:
      - 8083:8080
    volumes:
      - ./hub/backups:/hub/backups:rw
      - ./hub/data:/hub/data:rw
      - ./hub/logs:/hub/logs:rw
      - ./hub/conf:/hub/conf:rw
      - ./hub/temp:/hub/temp:rw
    restart: always
    cpu_shares: 75
    mem_limit: 1g
    memswap_limit: 2g

  youtrack:
    container_name: youtrack
    image: pojo-youtrack:latest
    build:
      context: .
      dockerfile: Dockerfile-youtrack
    ports:
      - 8080:8080
    volumes:
      - ./youtrack/backups:/youtrack/backups:rw
      - ./youtrack/data:/youtrack/data:rw
      - ./youtrack/logs:/youtrack/logs:rw
      - ./youtrack/conf:/youtrack/conf:rw
      - ./youtrack/temp:/youtrack/temp:rw
    restart: always
    links:
      - teamcity
      - hub
    cpu_shares: 75
    mem_limit: 1g
    memswap_limit: 2g

  upsource:
    container_name: upsource
    image: pojo-upsource:latest
    build:
      context: .
      dockerfile: Dockerfile-upsource
    ports:
      - 8082:8080
    volumes:
      - ./upsource/backups:/upsource/backups:rw
      - ./upsource/data:/upsource/data:rw
      - ./upsource/logs:/upsource/logs:rw
      - ./upsource/conf:/upsource/conf:rw
      - ./upsource/temp:/upsource/temp:rw
    restart: always
    links:
      - youtrack
      - teamcity
      - hub
    cpu_shares: 50
    mem_limit: 4g
    memswap_limit: 8g

  teamcity:
    container_name: teamcity
    image: pojo-teamcity:latest
    build:
      context: .
      dockerfile: Dockerfile-teamcity
    ports:
      - 8081:8111
    volumes:
      - ./teamcity/plugins:/teamcity/plugins:rw
      - ./teamcity/conf:/teamcity/conf:rw
      - ./teamcity/logs:/teamcity/logs:rw
    restart: always
    links:
      - postgres
      - hub
    cpu_shares: 75
    mem_limit: 1g
    memswap_limit: 2g

  teamcity-agent:
    image: jetbrains/teamcity-agent:latest
    environment:
      - "SERVER_URL=teamcity:8111"
    restart: always
    links:
      - teamcity
    cpu_shares: 75
    mem_limit: 1g
    memswap_limit: 2g

  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
      - 5432:5432
    restart: always
    cpu_shares: 75
    mem_limit: 512m
    memswap_limit: 1g

#  nginx:
#    container_name: nginx
#    image: nginx
#    volumes:
#      - ./nginx:/etc/nginx
#    environment:
#      - NGINX_PORT=80
#    ports:
#      - 80:80
#    links:
#      - hub
#      - youtrack
#      - upsource
#      - teamcity
#    restart: always